export { default as Home } from './sections/Home';
export { default as AIAutomation } from './sections/AIAutomation';
export { default as CustomDevelopment } from './sections/CustomDevelopment';
export { default as Solutions } from './sections/Solutions';
export { default as CaseStudies } from './sections/CaseStudies';
export { default as About } from './sections/About';
export { default as Contact } from './sections/Contact';
export { default as Blog } from './sections/Blog';
export { default as ThemeToggle } from './ui/ThemeToggle';